### ISSUE TITLE
Python package sympy missing from onnxruntime-training

### ISSUE THREAD

**Issue by kaiidams** [microsoft/containerregistry#50]
The package is required by this example,
https://github.com/microsoft/onnxruntime-training-examples/blob/4dae9249b75174a2b7f13012138831063cd14794/nvidia-bert/ort_addon/run_pretraining_ort.py#L40

To reproduce, run the following. `latest` has the same issue.
```
$ docker run --rm -it mcr.microsoft.com/azureml/onnxruntime-training:0.1-rc3.1-openmpi4.0-cuda10.2-cudnn8.0-nccl2.7-for-bert
root@81aac0b74186:/workspace# python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from onnxruntime.training.checkpoint import experimental_state_dict, experimental_load_state_dict
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/training/__init__.py", line 9, in <module>
    from .orttrainer import ORTTrainer, TrainStepInfo
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/training/orttrainer.py", line 13, in <module>
    from onnxruntime.tools.symbolic_shape_infer import SymbolicShapeInference
  File "/opt/conda/lib/python3.7/site-packages/onnxruntime/tools/symbolic_shape_infer.py", line 10, in <module>
    import sympy
ModuleNotFoundError: No module named 'sympy'
```

**Comment by bariscaglar** [comment]
@manashgoswami Is this something your team can help with?

**Comment by terencet-dev** [comment]
Hi, my name is Terence and I am the PM for Microsoft Artifact Registry (also known as Microsoft Container Registry or MCR).

Closing this issue as this is older than one year. Please feel free to open another GitHub issue if this is not correctly resolved.
